name: quick
version: 1.0.0+1
publish_to: none
description: A messaging app made with Flutter.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  #! Dependencies  
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_local_notifications: ^15.1.0+1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  lottie: ^2.5.0
  firebase_analytics: ^10.4.4
  google_fonts: ^5.1.0
  dio: ^5.3.0
  heroicons: ^0.8.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

